### ISSUE TITLE
Admin interface tracker

### ISSUE THREAD

**Issue by tudurom** [StudieverenigingSTORM/knt#14]
- [x] Research - what tech to use
- [ ] Beautification
- [x] Initial design
- [x] Dummy implementation with dummy data

**Comment by tudurom** [comment]
@Nico213 Please write about the research findings and maybe initial design here to have it in one place.

**Comment by Nico213** [comment]
We are using the python simpleGui library to use for its simplicity. Alternatively, we could have used Tkinter (native to python), but the extra dependency of simpleGui is well worth it compared to just using Tkinter is well worth is since simpleGui (dependent on port) is build directly on top of Tkinter to make it much more friendly to use. 
Another alternative could have been Qt. If for whatever reason it is ever necessary to switch framework simpleGui should* offer exports options for both Qt and Tkinter. So all in all it's an all-rounder of a choice.

**Comment by Nico213** [comment]
For the initial design, I have mostly gone off two very crappy pictures I took from the old system:

Products:
![image](https://user-images.githubusercontent.com/60398347/154803066-bbf786e7-1300-48b8-9a58-78b27a613553.png)

Users: (a list of all user names is to left out of view)
![image](https://user-images.githubusercontent.com/60398347/154803159-decd5308-bd2d-4846-b88b-01f39d37186f.png)

**Comment by Nico213** [comment]
As of writing the products tab is still under heavy construction but the user tab's first implementation based on dummy data is pretty well along. 

Upon opening the application looks as follows:
![image](https://user-images.githubusercontent.com/60398347/154803285-7fbe50f7-cfc1-4641-aa7f-2281801cc535.png)

selecting a user out of the list by either manually searching or using the filter for name or vunetid gives:
![image](https://user-images.githubusercontent.com/60398347/154803501-04915006-7b3a-43f5-8dfb-d3d93193f3db.png)

add user yields a pop up
![image](https://user-images.githubusercontent.com/60398347/154803345-c679c7b5-abe9-4c93-bd6a-4d316773653f.png)

something similar is planned for change pin and delete user.

The product tab is still empty

**Comment by Nico213** [comment]
Added product tab. Everything works on dummy data still.
Needs to switch over to the actual DB/backend.
Needs a little make-over, the current theme is a bit boring.

**Comment by TadMaj** [comment]
Admin interface required auth

- [x] Authorization with board passwords
- [x] Time based session timeouts

**Comment by TadMaj** [comment]
The admin interface panel is being moved to its own separate project.
